### PR TITLE
Use the latest notification plugin release

### PR DESCRIPTION
**Pull request by dangeross**
This PR changes the podfile/gradle (BreezSDKLiquid/breez-sdk-liquid) notification plugin dependencies to use the latest release

(To be merged post 0.2.2 release)

### CODE REVIEW

**Comment by erdemyerebasmaz** [comment]
@dangeross are these changes ready for review?

**Comment by dangeross** [comment]
@erdemyerebasmaz I need to test in the morning if it works correctly

**Comment by dangeross** [comment]
Tested. Seems to pull the latest release

**Comment by erdemyerebasmaz** [comment]
> Tested. Seems to pull the latest release

Both on iOS & Android?

**Comment by dangeross** [comment]
> Both on iOS & Android?

Yep, both pulled in 0.3.0

**Review by erdemyerebasmaz — APPROVED** [review]

**Pull request merged**
