### PR TITLE
Add Android notification plugin

### PR DESCRIPTION
**Pull request by dangeross**
This PR adds the SDK notification plugin into the Android build of Misty Breez. I've updated the gradle config and LN address/webhook registration to be consistent with c-breez. Tested handling LNURL-pay requests, it still doesn't receive swap-updates because https://github.com/breez/notify/pull/13 needs merging.

This currently needs to build along side https://github.com/breez/breez-sdk-liquid/tree/savage-android-notification-plugin

### CODE REVIEW

**Comment by dangeross** [comment]
@erdemyerebasmaz I need a little help fixing this layout, them not sure how to make it page width.

signal-2024-08-14-080317

**Review by erdemyerebasmaz — CHANGES_REQUESTED** [review]
Looks good but I think we should update the notification icon to use Misty Breez's colors.

**Comment by dangeross** [comment]
> Looks good but I think we should update the notification icon to use Misty Breez's colors.

@erdemyerebasmaz are you able to do that?

**Comment by erdemyerebasmaz** [comment]
> > Looks good but I think we should update the notification icon to use Misty Breez's colors.
> 
> @erdemyerebasmaz are you able to do that?

Yes, I'll look into it.

**Comment by erdemyerebasmaz** [comment]
> > > Looks good but I think we should update the notification icon to use Misty Breez's colors.
> > 
> > 
> > @erdemyerebasmaz are you able to do that?
> 
> Yes, I'll look into it.

Done. 
- [Change notification icon on Android](https://github.com/breez/misty-breez/pull/150/commits/80a2916b3f2612a164811eaba25aee2ba5dcfcfd)

**Review by roeierez — APPROVED** [review]

**Review by erdemyerebasmaz — APPROVED** [review]

**Pull request merged**
