### PR TITLE
Do not emit payment state changes unless there's been a change

### PR DESCRIPTION
**Pull request by erdemyerebasmaz**
Added equality operators to `PaymentsState` items, `PaymentData` & `PaymentFilters` so the state is updated on distinct `PaymentsState` events on `PaymentCubit`.

### CODE REVIEW

**Comment by dangeross** [comment]
Seems to be a conflict

**Comment by erdemyerebasmaz** [comment]
> Seems to be a conflict

It was caused by a difference in imports due to changes in #129.
Resolved.

**Review by dangeross — APPROVED** [review]
LGTM. So I'm assuming a change to something like the payment status triggers the emit.  Just a side question, is the payment state replaced when a payment update is emitted (how is an old payment updated)?

**Comment by erdemyerebasmaz** [comment]
> LGTM. So I'm assuming a change to something like the payment status triggers the emit.
> 
> Just a side question, is the payment state replaced when a payment update is emitted (how is an old payment updated)?

Yes, any changes on a payment list-could be the addition of a new payment or a change on an existing payment- or payment filter will emit a new state.

Yes, state is replaced. `listPayments` response will be mapped to a list of `PaymentData`, app's internal helper class for payments, and this will replace existing `paymentList` value on state.

**Pull request merged**
